version: '3'

services:

  datagrid1:
    container_name: datagrid1
    image: registry.redhat.io/datagrid/datagrid-8-rhel8:1.2-8.2.1.GA.2
    hostname: datagrid1
    environment:
      USER: developer
      PASS: developer
    ports:
      - 11222:11222
    networks:
      - rhdg-meter
   

  datagrid2:
    container_name: datagrid2
    image: registry.redhat.io/datagrid/datagrid-8-rhel8:1.2-8.2.1.GA.2
    hostname: datagrid2
    environment:
      USER: developer
      PASS: developer
    ports:
      - 11223:11222
    networks:
      - rhdg-meter
    depends_on:
      - datagrid1

    
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    hostname: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:z
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    # ports:
    #   - 9090:9090
    network_mode: host

  grafana:
    container_name: grafana
    image: grafana/grafana
    hostname: grafana
    depends_on:
      - prometheus
    # ports:
    #   - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/:z
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
    network_mode: host
  
networks:
  rhdg-meter:
    driver: bridge