{
 "title": "Infinispan - General",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": "label_values(pod)" },
   {
    "name": "cache_name",
    "label": "cache_name",
    "query": "metrics(vendor_cache_manager_default_cache_.*_statistics_number_of_entries_in_memory)"
   }
  ]
 },
 "panels": [
  {
   "title": "Instances (up)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vendor_cache_manager_default_cache_container_health_number_of_nodes",
     "legendFormat": "Instances (up)"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(vendor_cache_manager_default_cache_container_health_number_of_cpus)",
     "legendFormat": "CPUs"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(vendor_cache_manager_default_cache_container_health_total_memory_kb/1000)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Caches",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_number_of_entries_in_memory\",pod=~\"$instance\"},\"cache_name\", \"$1\", \"__name__\", \"vendor_cache_manager_default_cache_(.*)_statistics_number_of_entries_in_memory\")"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threading on $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "base_thread_daemon_count{pod=~\"$nstance\"}",
       "legendFormat": "Daemon Threads"
      },
      {
       "expr": "base_thread_count{pod=~\"$instance\"}",
       "legendFormat": "Thread Count"
      },
      {
       "expr": "base_thread_max_count{pod=~\"$instance\"}",
       "legendFormat": "Max Count"
      }
     ]
    },
    {
     "title": "Threading on $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "base_thread_daemon_count{pod=~\"$nstance\"}",
       "legendFormat": "Daemon Threads"
      },
      {
       "expr": "base_thread_count{pod=~\"$instance\"}",
       "legendFormat": "Thread Count"
      },
      {
       "expr": "base_thread_max_count{pod=~\"$instance\"}",
       "legendFormat": "Max Count"
      }
     ]
    },
    {
     "title": "Threading on $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "base_thread_daemon_count{pod=~\"$nstance\"}",
       "legendFormat": "Daemon Threads"
      },
      {
       "expr": "base_thread_count{pod=~\"$instance\"}",
       "legendFormat": "Thread Count"
      },
      {
       "expr": "base_thread_max_count{pod=~\"$instance\"}",
       "legendFormat": "Max Count"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Global Memory on $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
     "repeat": "instance",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "base_memory_usedNonHeap_bytes{pod=~\"$instance\"}",
       "legendFormat": "Non Heap used"
      },
      {
       "expr": "base_memory_usedHeap_bytes{pod=~\"$instance\"}",
       "legendFormat": "Heap used"
      }
     ]
    },
    {
     "title": "Global Memory on $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "base_memory_usedNonHeap_bytes{pod=~\"$instance\"}",
       "legendFormat": "Non Heap used"
      },
      {
       "expr": "base_memory_usedHeap_bytes{pod=~\"$instance\"}",
       "legendFormat": "Heap used"
      }
     ]
    },
    {
     "title": "Global Memory on $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "base_memory_usedNonHeap_bytes{pod=~\"$instance\"}",
       "legendFormat": "Non Heap used"
      },
      {
       "expr": "base_memory_usedHeap_bytes{pod=~\"$instance\"}",
       "legendFormat": "Heap used"
      }
     ]
    },
    {
     "title": "Memory Pools on $instance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "repeat": "instance",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "vendor_memoryPool_CodeHeap_non_nmethods_usage_bytes{pod=~\"$instance\"}",
       "legendFormat": "Code Heap non-nmethods"
      },
      {
       "expr": "vendor_memoryPool_CodeHeap_profiled_nmethods_usage_bytes{pod=~\"$instance\"}",
       "legendFormat": "Code Heap profiled nmethods"
      },
      {
       "expr": "vendor_memoryPool_CodeHeap_non_profiled_nmethods_usage_bytes{pod=~\"$instance\"}",
       "legendFormat": "Code Heap non-profiled nmethods"
      },
      {
       "expr": "vendor_memoryPool_Compressed_Class_Space_usage_bytes{pod=~\"$instance\"}",
       "legendFormat": "Compressed Class"
      },
      {
       "expr": "vendor_memoryPool_Metaspace_usage_bytes{pod=~\"$instance\"}",
       "legendFormat": "Metaspace"
      },
      {
       "expr": "vendor_memoryPool_Tenured_Gen_usage_bytes{pod=~\"$instance\"}",
       "legendFormat": "Tenured"
      },
      {
       "expr": "vendor_memoryPool_Survivor_Space_usage_bytes{pod=~\"$instance\"}",
       "legendFormat": "Survivor"
      },
      {
       "expr": "vendor_memoryPool_Eden_Space_usage_bytes{pod=~\"$instance\"}",
       "legendFormat": "Eden"
      }
     ]
    },
    {
     "title": "Memory Pools on $instance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "vendor_memoryPool_CodeHeap_non_nmethods_usage_bytes{pod=~\"$instance\"}",
       "legendFormat": "Code Heap non-nmethods"
      },
      {
       "expr": "vendor_memoryPool_CodeHeap_profiled_nmethods_usage_bytes{pod=~\"$instance\"}",
       "legendFormat": "Code Heap profiled nmethods"
      },
      {
       "expr": "vendor_memoryPool_CodeHeap_non_profiled_nmethods_usage_bytes{pod=~\"$instance\"}",
       "legendFormat": "Code Heap non-profiled nmethods"
      },
      {
       "expr": "vendor_memoryPool_Compressed_Class_Space_usage_bytes{pod=~\"$instance\"}",
       "legendFormat": "Compressed Class"
      },
      {
       "expr": "vendor_memoryPool_Metaspace_usage_bytes{pod=~\"$instance\"}",
       "legendFormat": "Metaspace"
      },
      {
       "expr": "vendor_memoryPool_Tenured_Gen_usage_bytes{pod=~\"$instance\"}",
       "legendFormat": "Tenured"
      },
      {
       "expr": "vendor_memoryPool_Survivor_Space_usage_bytes{pod=~\"$instance\"}",
       "legendFormat": "Survivor"
      },
      {
       "expr": "vendor_memoryPool_Eden_Space_usage_bytes{pod=~\"$instance\"}",
       "legendFormat": "Eden"
      }
     ]
    },
    {
     "title": "Memory Pools on $instance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "vendor_memoryPool_CodeHeap_non_nmethods_usage_bytes{pod=~\"$instance\"}",
       "legendFormat": "Code Heap non-nmethods"
      },
      {
       "expr": "vendor_memoryPool_CodeHeap_profiled_nmethods_usage_bytes{pod=~\"$instance\"}",
       "legendFormat": "Code Heap profiled nmethods"
      },
      {
       "expr": "vendor_memoryPool_CodeHeap_non_profiled_nmethods_usage_bytes{pod=~\"$instance\"}",
       "legendFormat": "Code Heap non-profiled nmethods"
      },
      {
       "expr": "vendor_memoryPool_Compressed_Class_Space_usage_bytes{pod=~\"$instance\"}",
       "legendFormat": "Compressed Class"
      },
      {
       "expr": "vendor_memoryPool_Metaspace_usage_bytes{pod=~\"$instance\"}",
       "legendFormat": "Metaspace"
      },
      {
       "expr": "vendor_memoryPool_Tenured_Gen_usage_bytes{pod=~\"$instance\"}",
       "legendFormat": "Tenured"
      },
      {
       "expr": "vendor_memoryPool_Survivor_Space_usage_bytes{pod=~\"$instance\"}",
       "legendFormat": "Survivor"
      },
      {
       "expr": "vendor_memoryPool_Eden_Space_usage_bytes{pod=~\"$instance\"}",
       "legendFormat": "Eden"
      }
     ]
    },
    {
     "title": "Garbage Collection on $instance",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(base_gc_total{pod=~\"$instance\"}[45s])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Garbage Collection on $instance",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(base_gc_total{pod=~\"$instance\"}[45s])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Garbage Collection on $instance",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(base_gc_total{pod=~\"$instance\"}[45s])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}